#!/usr/bin/env python3
"""Create an Alpine/APK v2 package from an install-root directory.

Vendored from kn6plv/MakeAPK (MIT License) so Crow's AREDN build can
produce APK artifacts without requiring a separately installed mkapk.py.
"""

import argparse
import gzip
import hashlib
import io
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile
import time


BLOCK = 512
NULLBLOCK = b"\0" * BLOCK

INSTALL_SCRIPTS = (
    ".pre-install",
    ".post-install",
    ".pre-deinstall",
    ".post-deinstall",
    ".pre-upgrade",
    ".post-upgrade",
    ".trigger",
)


def make_tar_bytes(root, relpaths, *, include_hash, include_eof, build_epoch):
    buf = io.BytesIO()
    tf = tarfile.open(fileobj=buf, mode="w", format=tarfile.PAX_FORMAT)

    for relpath in relpaths:
        fullpath = os.path.join(root, relpath)
        info = tf.gettarinfo(name=fullpath, arcname=relpath)
        info.uid = 0
        info.gid = 0
        info.uname = "root"
        info.gname = "root"
        info.mtime = build_epoch

        if info.isreg():
            with open(fullpath, "rb") as fh:
                filedata = fh.read()
            if include_hash:
                info.pax_headers["APK-TOOLS.checksum.SHA1"] = hashlib.sha1(filedata).hexdigest()
            tf.addfile(info, io.BytesIO(filedata))
        else:
            tf.addfile(info)

    tf.close()
    data = buf.getvalue()

    if not include_eof:
        end = len(data)
        while end >= BLOCK and data[end - BLOCK:end] == NULLBLOCK:
            end -= BLOCK
        data = data[:end]

    return data


def gzip_compress(data):
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(data)
    return buf.getvalue()


def walk_sorted(root):
    paths = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        rel = os.path.relpath(dirpath, root)
        if rel != ".":
            paths.append(rel)
        for filename in sorted(filenames):
            paths.append(os.path.join(rel, filename) if rel != "." else filename)
    return paths


def dir_size(path):
    total = 0
    for dirpath, _, filenames in os.walk(path):
        for filename in filenames:
            filepath = os.path.join(dirpath, filename)
            if not os.path.islink(filepath):
                total += os.path.getsize(filepath)
    return total


def build_pkginfo(*, name, version, release, desc, url, arch, license_, maintainer,
                  installed_size, datahash, depends, build_epoch):
    lines = [
        "# Generated by mkapk",
        f"pkgname = {name}",
        f"pkgver = {version}-{release}",
        f"pkgdesc = {desc}",
        f"url = {url}",
        f"builddate = {build_epoch}",
        "packager = mkapk",
        f"size = {installed_size}",
        f"arch = {arch}",
        f"origin = {name}",
        f"maintainer = {maintainer}",
        f"license = {license_}",
        f"datahash = {datahash}",
    ]
    for dep in depends:
        dep = dep.strip()
        if dep:
            lines.append(f"depend = {dep}")
    return "\n".join(lines) + "\n"


def sign_control(control_gz, keyfile, build_epoch):
    key_basename = os.path.basename(keyfile)
    if key_basename.endswith(".rsa"):
        key_basename = key_basename[:-4]
    sig_name = f".SIGN.RSA.{key_basename}.pub"

    with tempfile.NamedTemporaryFile() as ctrl_tmp, tempfile.NamedTemporaryFile() as sig_tmp:
        ctrl_tmp.write(control_gz)
        ctrl_tmp.flush()
        subprocess.run(
            ["openssl", "dgst", "-sha1", "-sign", keyfile, "-out", sig_tmp.name, ctrl_tmp.name],
            check=True,
        )
        with open(sig_tmp.name, "rb") as fh:
            sig_data = fh.read()

    buf = io.BytesIO()
    tf = tarfile.open(fileobj=buf, mode="w", format=tarfile.PAX_FORMAT)
    info = tarfile.TarInfo(name=sig_name)
    info.size = len(sig_data)
    info.mode = 0o644
    info.uid = 0
    info.gid = 0
    info.uname = "root"
    info.gname = "root"
    info.mtime = build_epoch
    tf.addfile(info, io.BytesIO(sig_data))
    tf.close()

    raw = buf.getvalue()
    end = len(raw)
    while end >= BLOCK and raw[end - BLOCK:end] == NULLBLOCK:
        end -= BLOCK
    return gzip_compress(raw[:end])


def info(msg):
    print(f"==> {msg}", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(
        prog="mkapk",
        description="Create an Alpine Linux APK v2 package from a directory.",
    )
    parser.add_argument("-n", "--name", required=True)
    parser.add_argument("-v", "--version", required=True)
    parser.add_argument("-d", "--directory", required=True)
    parser.add_argument("-a", "--arch", default="x86_64")
    parser.add_argument("-r", "--release", default="r0")
    parser.add_argument("-D", "--desc", default=None)
    parser.add_argument("-u", "--url", default="https://localhost")
    parser.add_argument("-l", "--license", default="MIT", dest="license_")
    parser.add_argument("-m", "--maintainer", default="Unknown <unknown@localhost>")
    parser.add_argument("-p", "--depends", default="")
    parser.add_argument("-o", "--outdir", default=".")
    parser.add_argument("-k", "--key", default=None)
    args = parser.parse_args()

    try:
        build_epoch = int(os.environ.get("SOURCE_DATE_EPOCH", str(int(time.time()))))
    except ValueError as exc:
        parser.error(f"SOURCE_DATE_EPOCH must be an integer: {exc}")

    src = os.path.abspath(args.directory)
    if not os.path.isdir(src):
        parser.error(f"source directory '{args.directory}' does not exist")

    desc = args.desc or f"{args.name} package"
    depends = [d.strip() for d in args.depends.split(",") if d.strip()] if args.depends else []
    outdir = os.path.abspath(args.outdir)
    os.makedirs(outdir, exist_ok=True)

    work = tempfile.mkdtemp(prefix="mkapk-")
    try:
        data_dir = os.path.join(work, "data")
        ctrl_dir = os.path.join(work, "control")
        shutil.copytree(src, data_dir, symlinks=True, dirs_exist_ok=True)
        os.makedirs(ctrl_dir, exist_ok=True)

        for script in INSTALL_SCRIPTS:
            src_script = os.path.join(data_dir, script)
            if os.path.isfile(src_script):
                dst_script = os.path.join(ctrl_dir, script)
                shutil.move(src_script, dst_script)
                os.chmod(dst_script, 0o755)

        info("Collecting files")
        manifest_rel = f"lib/apk/packages/{args.name}.list"
        manifest_abs = os.path.join(data_dir, manifest_rel)
        os.makedirs(os.path.dirname(manifest_abs), exist_ok=True)

        pre_paths = walk_sorted(data_dir)
        if not pre_paths:
            parser.error("source directory is empty")

        manifest_lines = [
            path for path in pre_paths
            if not os.path.isdir(os.path.join(data_dir, path))
        ]
        with open(manifest_abs, "w", encoding="utf-8") as fh:
            fh.write("\n".join(manifest_lines) + "\n")

        data_paths = walk_sorted(data_dir)
        data_tar = make_tar_bytes(
            data_dir, data_paths, include_hash=True, include_eof=True,
            build_epoch=build_epoch,
        )
        data_gz = gzip_compress(data_tar)
        datahash = hashlib.sha256(data_gz).hexdigest()
        installed_size = dir_size(data_dir)

        info("Generating .PKGINFO")
        pkginfo = build_pkginfo(
            name=args.name,
            version=args.version,
            release=args.release,
            desc=desc,
            url=args.url,
            arch=args.arch,
            license_=args.license_,
            maintainer=args.maintainer,
            installed_size=installed_size,
            datahash=datahash,
            depends=depends,
            build_epoch=build_epoch,
        )
        with open(os.path.join(ctrl_dir, ".PKGINFO"), "w", encoding="utf-8") as fh:
            fh.write(pkginfo)

        ctrl_paths = sorted(
            entry for entry in os.listdir(ctrl_dir)
            if os.path.isfile(os.path.join(ctrl_dir, entry))
        )
        ctrl_tar = make_tar_bytes(
            ctrl_dir, ctrl_paths, include_hash=False, include_eof=False,
            build_epoch=build_epoch,
        )
        ctrl_gz = gzip_compress(ctrl_tar)

        sig_gz = None
        if args.key:
            if not os.path.isfile(args.key):
                parser.error(f"signing key '{args.key}' not found")
            if not shutil.which("openssl"):
                parser.error("openssl is required for signing")
            info(f"Signing with {args.key}")
            sig_gz = sign_control(ctrl_gz, args.key, build_epoch)

        apk_name = f"{args.name}-{args.version}-{args.release}.apk"
        apk_path = os.path.join(outdir, apk_name)

        info(f"Assembling {apk_name}")
        with open(apk_path, "wb") as fh:
            if sig_gz:
                fh.write(sig_gz)
            fh.write(ctrl_gz)
            fh.write(data_gz)

        apk_size = os.path.getsize(apk_path)
        signed = "yes" if sig_gz else "no"
        info(f"Done! {apk_path} ({apk_size} bytes)")
        print()
        print(f"  Package : {args.name}")
        print(f"  Version : {args.version}-{args.release}")
        print(f"  Arch    : {args.arch}")
        print(f"  Signed  : {signed}")
        print()
        print(f"Install with: apk add --allow-untrusted {apk_path}")
    finally:
        shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    main()
